---
- name: Setup Fedora Server Environment
  tasks:
    - name: Ensure all packages are up to date
      ansible.builtin.dnf5:
        name: "*"
        state: present
        update_cache: yes

    - name: Install required packages
      ansible.builtin.dnf5:
        name:
          - zsh

    - name: Install ansible plugins
      become: yes
